---
- include: "{{ deploy_initialize_before | default('../hooks/example.yml') }}"
  tags: deploy-initialize-before

- name: Initialize
  deploy_helper:
    current_path: "{{ project_current_path }}"
    path: "{{ project_root }}"
    state: present

- include: "{{ deploy_initialize_after | default('../hooks/example.yml') }}"
  tags: deploy-initialize-after
