mariadb_binary_logging_disabled: true
mariadb_keyserver_fingerprint: "0xcbcb082a1bb943db"
mariadb_mirror: nyc2.mirrors.digitalocean.com
mariadb_version: "10.0"
mariadb_dist: trusty
mysql_root_user: root

sites_using_remote_db: "[{% for name, site in wordpress_sites.iteritems() if site.env is defined and site.env.db_host | default('localhost') != 'localhost' %}'{{ name }}',{% endfor %}]"
