- name: composer
  src: geerlingguy.composer
  version: 1.2.7

- name: ntp
  src: resmo.ntp
  version: 0.3.0

- name: logrotate
  src: nickhammond.logrotate
  version: fc3ea4

- name: swapfile
  src: kamaln7.swapfile
  version: 0.4

- src: geerlingguy.daemonize
  version: 1.1.0

- name: mailhog
  src: geerlingguy.mailhog
  version: 1.1.0
